### ISSUE TITLE
problem at udev detection stage?

### ISSUE THREAD

**Issue by 4gra** [tiziano88/magic-trackpad-2-linux#1]
I can recreate the problem (via bluetooth or USB), on Ubuntu 15.10 "Wily".

I think the key here is that udev is categorising the device as a generic HID mouse and not a trackpad (setting `ENV{ID_INPUT_MOUSE}` rather than `ENV{ID_INPUT_TOUCHPAD}` for example).  By the time it gets to X and the synaptics driver, there aren't even any relevant events being generated, as you point out, so there's no chance of fixing it there.

Whether this is because it's simply being miscategorised (though I've not been able to clone the Magic Trackpad hwdb entries for the MT2 USB ID), or whether the trackpad requires some non-standard commands to "enable trackpad mode", I can't tell - but I certainly haven't excluded the former yet.

(relevant: https://answers.launchpad.net/ubuntu/+question/274078).

**Comment by tiziano88** [comment]
Thanks @4gra , I suspect the latter, namely that the device requires some non-standard way of switching it into trackpad mode. I would hope that at least those commands are still passed over HID, in which case we may be able to figure them out and replay them from any host, but I haven't verified that.

**Comment by tiziano88** [comment]
Some more info: https://bugzilla.redhat.com/show_bug.cgi?id=1274448

**Comment by ryanNLj** [comment]
only 3 people trying to use trackpad 2 on linux -_-???

**Comment by 4gra** [comment]
Since this issue seems to be mainly about collecting references: https://bugzilla.kernel.org/show_bug.cgi?id=112481 is the inevitable Linux kernel bug.  Hopefully that will help in some attention there will help in getting to the bottom of things.  Note the reference there to similar issues with the (built-in) force touch trackpad in the 2015 MBP.

**Comment by 4gra** [comment]
We're well and truly past this stage, and the hardware support's in the kernel.  So... closing.  Thanks all.
